### PR TITLE
Switch to npm ci

### PR DESCRIPTION
**Pull request by blakemorgan**
Switching to yarn because of its benefits over NPM (including caching and a better lock file).

### CODE REVIEW

**Comment by Gi60s** [comment]
I'm not sure if I agree with this change. My understanding is that NPM has gained back most of the popularity it lost when yarn first came out.

Can you provide evidence for why yarn is better?

**Comment by Gi60s** [comment]
https://medium.com/@vincentnewkirk/npm-vs-yarn-2019-e88757b17038

**Comment by blakemorgan** [comment]
I've seen that article before too. I just thought that Yarn has an offline cache so it doesn't need to send an HTTP request every time to get the package (https://yarnpkg.com/lang/en/docs/cli/cache/). Also, easier diffing (https://yarnpkg.com/blog/2017/05/31/determinism/). But I'm really fine with whatever.

**Comment by Gi60s** [comment]
Yarn does have caching and can run much faster than `npm install` but I believe that [`npm ci`](https://docs.npmjs.com/cli/ci.html) is just as fast as yarn's install. It's probably what we should be using in place of `npm install` too.

**Comment by blakemorgan** [comment]
OK. I've switched it back to NPM, updated the readme to use `npm ci` instead, and ran `npm audit fix`.

**Review by Gi60s — APPROVED** [review]

**Pull request merged**
